WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/train.py", line 24, in <module>
    from datasets import SKUDataset, TEST_TRANSFORM, TRAIN_TRANSFORM, VAL_TRANSFORM, custom_collate_fn
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>
    import cv2Traceback (most recent call last):

  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/train.py", line 24, in <module>
ModuleNotFoundError: No module named 'cv2'
    from datasets import SKUDataset, TEST_TRANSFORM, TRAIN_TRANSFORM, VAL_TRANSFORM, custom_collate_fn
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/train.py", line 24, in <module>
    import cv2
    ModuleNotFoundErrorfrom datasets import SKUDataset, TEST_TRANSFORM, TRAIN_TRANSFORM, VAL_TRANSFORM, custom_collate_fn: 
No module named 'cv2'  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>

    import cv2
ModuleNotFoundError: No module named 'cv2'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3584323) of binary: /work/cvcs_2023_group23/environments/cvcs_env/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-01-20_20:33:17
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3584328)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-01-20_20:33:17
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3584329)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-20_20:33:17
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3584323)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 21, in <module>
    from datasets import SKUDataset, TEST_TRANSFORM, custom_collate_fn
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 21, in <module>
    from datasets import SKUDataset, TEST_TRANSFORM, custom_collate_fn
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 21, in <module>
    from datasets import SKUDataset, TEST_TRANSFORM, custom_collate_fn
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3586434) of binary: /work/cvcs_2023_group23/environments/cvcs_env/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
evaluate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-01-20_20:33:42
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3586435)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-01-20_20:33:42
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3586436)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-20_20:33:42
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3586434)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
