WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/train.py", line 24, in <module>
    from datasets import SKUDataset, TEST_TRANSFORM, TRAIN_TRANSFORM, VAL_TRANSFORM, custom_collate_fn
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/train.py", line 24, in <module>
    from datasets import SKUDataset, TEST_TRANSFORM, TRAIN_TRANSFORM, VAL_TRANSFORM, custom_collate_fn
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/train.py", line 24, in <module>
    from datasets import SKUDataset, TEST_TRANSFORM, TRAIN_TRANSFORM, VAL_TRANSFORM, custom_collate_fn
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/datasets.py", line 12, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3590029) of binary: /work/cvcs_2023_group23/environments/cvcs_env/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-01-20_20:34:09
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3590030)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-01-20_20:34:09
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3590035)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-20_20:34:09
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3590029)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=FasterRCNN_ResNet50_FPN_Weights.COCO_V1`. You can also use `weights=FasterRCNN_ResNet50_FPN_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=FasterRCNN_ResNet50_FPN_Weights.COCO_V1`. You can also use `weights=FasterRCNN_ResNet50_FPN_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=FasterRCNN_ResNet50_FPN_Weights.COCO_V1`. You can also use `weights=FasterRCNN_ResNet50_FPN_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /homes/sbghosh/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth
  0%|          | 0.00/160M [00:00<?, ?B/s]  4%|▍         | 6.74M/160M [00:00<00:02, 70.6MB/s]  9%|▊         | 13.8M/160M [00:00<00:02, 72.8MB/s] 13%|█▎        | 21.2M/160M [00:00<00:01, 74.9MB/s] 18%|█▊        | 29.0M/160M [00:00<00:01, 77.3MB/s]Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /homes/sbghosh/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth
Downloading: "https://download.pytorch.org/models/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth" to /homes/sbghosh/.cache/torch/hub/checkpoints/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth
  0%|          | 0.00/160M [00:00<?, ?B/s] 23%|██▎       | 36.4M/160M [00:00<00:01, 77.3MB/s]  0%|          | 0.00/160M [00:00<?, ?B/s]  5%|▌         | 8.05M/160M [00:00<00:01, 84.3MB/s] 27%|██▋       | 43.8M/160M [00:00<00:01, 76.4MB/s] 10%|▉         | 15.4M/160M [00:00<00:00, 162MB/s] 14%|█▎        | 21.6M/160M [00:00<00:01, 118MB/s]  32%|███▏      | 51.0M/160M [00:00<00:01, 75.4MB/s] 23%|██▎       | 36.0M/160M [00:00<00:00, 193MB/s] 22%|██▏       | 35.8M/160M [00:00<00:00, 132MB/s] 36%|███▋      | 58.2M/160M [00:00<00:01, 75.0MB/s] 36%|███▌      | 56.8M/160M [00:00<00:00, 205MB/s] 32%|███▏      | 50.5M/160M [00:00<00:00, 141MB/s] 41%|████      | 65.4M/160M [00:00<00:01, 74.7MB/s] 41%|████      | 65.3M/160M [00:00<00:00, 146MB/s] 45%|████▌     | 72.5M/160M [00:01<00:01, 74.2MB/s] 48%|████▊     | 76.3M/160M [00:00<00:00, 133MB/s] 50%|████▉     | 79.2M/160M [00:00<00:00, 137MB/s] 50%|████▉     | 79.6M/160M [00:01<00:01, 74.1MB/s] 54%|█████▍    | 86.7M/160M [00:01<00:01, 74.3MB/s] 57%|█████▋    | 91.4M/160M [00:00<00:00, 106MB/s] 58%|█████▊    | 92.4M/160M [00:00<00:00, 108MB/s] 59%|█████▊    | 93.8M/160M [00:01<00:00, 72.1MB/s] 63%|██████▎   | 101M/160M [00:01<00:00, 72.9MB/s]  65%|██████▍   | 104M/160M [00:00<00:00, 93.6MB/s] 65%|██████▍   | 104M/160M [00:00<00:00, 93.7MB/s] 68%|██████▊   | 108M/160M [00:01<00:00, 66.2MB/s] 71%|███████   | 113M/160M [00:01<00:00, 80.8MB/s] 71%|███████   | 114M/160M [00:01<00:00, 81.6MB/s] 72%|███████▏  | 114M/160M [00:01<00:00, 66.5MB/s] 76%|███████▌  | 121M/160M [00:01<00:00, 68.1MB/s] 76%|███████▌  | 122M/160M [00:01<00:00, 78.3MB/s] 77%|███████▋  | 123M/160M [00:01<00:00, 79.1MB/s] 80%|████████  | 128M/160M [00:01<00:00, 68.4MB/s] 81%|████████  | 130M/160M [00:01<00:00, 76.0MB/s] 82%|████████▏ | 131M/160M [00:01<00:00, 76.8MB/s] 85%|████████▍ | 135M/160M [00:01<00:00, 71.0MB/s] 86%|████████▌ | 137M/160M [00:01<00:00, 76.4MB/s] 87%|████████▋ | 138M/160M [00:01<00:00, 77.2MB/s] 89%|████████▉ | 142M/160M [00:02<00:00, 72.3MB/s] 91%|█████████ | 145M/160M [00:01<00:00, 76.0MB/s] 91%|█████████▏| 146M/160M [00:01<00:00, 76.5MB/s] 94%|█████████▍| 150M/160M [00:02<00:00, 73.8MB/s] 95%|█████████▌| 152M/160M [00:01<00:00, 75.8MB/s] 96%|█████████▌| 153M/160M [00:01<00:00, 76.2MB/s] 98%|█████████▊| 157M/160M [00:02<00:00, 73.8MB/s]100%|█████████▉| 159M/160M [00:01<00:00, 74.8MB/s]100%|██████████| 160M/160M [00:01<00:00, 94.1MB/s]
100%|██████████| 160M/160M [00:01<00:00, 92.1MB/s]
100%|██████████| 160M/160M [00:02<00:00, 72.6MB/s]
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 318, in <module>
    main()
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 297, in main
    model = load_model(
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 76, in load_model
    checkpoint = torch.load(checkpoint_path)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/checkpoints/frcnn/checkpoint.pth'
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 318, in <module>
    main()
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 297, in main
    model = load_model(
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 76, in load_model
    checkpoint = torch.load(checkpoint_path)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/checkpoints/frcnn/checkpoint.pth'
Traceback (most recent call last):
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 318, in <module>
    main()
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 297, in main
    model = load_model(
  File "/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/evaluate.py", line 76, in load_model
    checkpoint = torch.load(checkpoint_path)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/work/cvcs_2023_group23/ObjectDescriptionSupermarket-CVCS-UniMoRe/checkpoints/frcnn/checkpoint.pth'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3592254) of binary: /work/cvcs_2023_group23/environments/cvcs_env/bin/python
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/work/cvcs_2023_group23/environments/cvcs_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
evaluate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-01-20_20:34:39
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3592255)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-01-20_20:34:39
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3592256)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-20_20:34:39
  host      : aimagelab-srv-00.ing.unimore.it
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3592254)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
